### ISSUE TITLE
Check mimeType prior to sending requests

### ISSUE THREAD

**Issue by avishnyak** [Brzeczunio/insomnia-plugin-run-folder-graphql#2]
If someone has a folder with a mix of GraphQL and non-json requests, the plugin currently errors out because it tries to parse the response as JSON.

I propose adding a check for `request.body.mimeType = 'application/graphql'` for each request and skip trying to parse any response that is not a GraphQL request in this plugin. Simply show the HTTP status code and time for those.

I'm happy to send a PR, if you would like.

**Comment by Brzeczunio** [comment]
Thank you very much ! I've accepted pull request :) 👍
